from pydantic import BaseModel, ConfigDict, Field


class SimulationRequest(BaseModel):
    """Request payload for triggering a climate risk cascade simulation."""

    model_config = ConfigDict(extra="forbid")

    disaster_type: str = Field(
        ...,
        min_length=1,
        examples=["Category 4 Hurricane", "Flash Flood"],
        description="The type of climate disaster impacting the infrastructure grid.",
    )
    epicenter_node: str = Field(
        ...,
        min_length=1,
        examples=["Main Power Plant"],
        description="The starting infrastructure node at the epicenter of the disaster.",
    )


class NodeState(BaseModel):
    """Evaluated state of a single infrastructure node in the simulation trace."""

    model_config = ConfigDict(extra="forbid")

    node_name: str = Field(..., description="Identifier/name of the infrastructure node.")
    status: bool = Field(
        ...,
        description="Operational status of the node: False means failed, True means survived.",
    )
    reasoning: str = Field(
        ...,
        description="Explanation generated by the AI agent for why the node failed or survived.",
    )
