from typing import Any, Optional
from pydantic import BaseModel, ConfigDict, Field


class SimulationRequest(BaseModel):
    """Request payload for triggering a climate risk cascade simulation."""

    model_config = ConfigDict(extra="forbid")

    disaster_type: str = Field(
        ...,
        min_length=1,
        examples=["Hurricane", "Storm Surge Flood", "Tornado"],
        description="The type of climate disaster impacting the infrastructure grid.",
    )
    magnitude: str = Field(
        default="Category 5",
        min_length=1,
        examples=["Category 5", "EF-3", "Water level +2.5m"],
        description="Physical scale or intensity metric of the disaster.",
    )
    trajectory: str = Field(
        ...,
        min_length=1,
        examples=["Coming from the Atlantic East coast", "Approaching from Biscayne Bay (Southeast)"],
        description="Geographical trajectory or approach vector of the disaster.",
    )


class NodeState(BaseModel):
    """Evaluated state of a single infrastructure node in the self-healing simulation trace."""

    model_config = ConfigDict(extra="forbid")

    step: Optional[str] = Field(
        default="cascade",
        description="Type of trace step: 'impact' for initial meteorological epicenter hit, or 'cascade' for BFS propagation.",
    )
    node: Optional[str] = Field(
        default=None,
        description="Identifier/name of the impacted or evaluated node.",
    )
    parent_node: Optional[str] = Field(
        default=None,
        description="The failed upstream parent node that triggered this evaluation (None for epicenter).",
    )
    child_node: Optional[str] = Field(default=None, description="Identifier/name of the evaluated child node.")
    node_name: Optional[str] = Field(default=None, description="Identifier/name of the infrastructure node.")
    node_type: str = Field(default="unknown", description="Infrastructure category/type of the node.")
    magnitude: Optional[str] = Field(default=None, description="Disaster magnitude evaluated at this step.")
    status: bool = Field(
        default=False,
        description="Operational status of the node: False means failed, True means survived.",
    )
    reasoning: str = Field(
        ...,
        description="Physics or meteorological explanation generated by the AI agent (max 25 words).",
    )
    recovery_command: Optional[str] = Field(
        default=None,
        description="Terminal command generated by the self-healing AI to reroute supply on failure.",
    )
    new_edge: Optional[dict[str, Any]] = Field(
        default=None,
        description="New directed edge {'source': ..., 'target': ...} dynamically added to heal the graph.",
    )
